site_name: Gamifica Requisitos
site_url: https://mdsreq-fga-unb.github.io/2023.1-GamificaRequisitos/

nav:
  - Início: index.md
  - Visão do Produto: visao_produto.md
  - Visão do Projeto: visao_projeto.md
  - Processo de Desenvolvimento: processo_software.md
  - Product Backlog: backlog.md
  - MVPs: mvps.md
  - Apresentações: apresentacoes.md
  - Entregas:
    - Pit OpenUp: entrega_pitch_openUp.md
    - Visão Geral do Projeto: entrega_visao_geral_prod.md
    - Planejamento do Projeto: entrega_planej_proj.md
    - Mural: mural.md
  - Lições Aprendidas: licoes_aprendidas.md
  - Bibliografia: bibliografia.md

theme:
  name: material
  icon:
    logo: material/gamepad-square 
    favicon: images/favicon.png
  palette:
    - scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Modo noturno
    - scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Modo claro

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences